[package]
name = "e2e-tests"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
aws-lc-rs.workspace = true
base64 = "0.22"
nojson.workspace = true
raden = "2026.1"
shiguredo_http11.workspace = true
shiguredo_nvcodec = { workspace = true, optional = true }
shiguredo_video_device = "2026.1"
shiguredo_webrtc.workspace = true
sora_sdk.workspace = true
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
serial_test = "3.4"

[target.'cfg(target_os = "macos")'.dependencies]
shiguredo_audio_device = "2026.1"

[features]
default = []
amf = ["sora_sdk/amf"]
libcamera = ["sora_sdk/libcamera"]
nvcodec = ["dep:shiguredo_nvcodec", "sora_sdk/nvcodec"]
v4l2 = ["sora_sdk/v4l2"]
vpl = ["sora_sdk/vpl"]
